### ISSUE TITLE
Discussion about the implementation 

### ISSUE THREAD

**Issue by ranhsd** [parse-server-modules/parse-server-gcloud-pubsub#1]
Hi @flovilmart , 

About creating new topics . I don't know if we need to create a new topic each time the user publish a new message. What i noticed is that we have 2 channels "afterSave" and "afterDelete" so we need to create a topic for each of the channels. The question is if we really have only 2 channels or more?

**Comment by flovilmart** [comment]
We should attempt to create the topic at the 1st time we need it, but otherwise, we should reuse an existing one. 

The publisher will publish on those, and subscribers will listen to those publications.

**Comment by ranhsd** [comment]
Ok , and after reading a lot some docs about the Google pub sub I understand that we need to use pub sub push (and not pull) because the push is more "real time" and this is what we need for live query.. the only thing that you need to do if you want to use the push is to provide endpoint URL now this endpoint must be secured (https) and the recommendation is to have an app on Google app engine for that purpose. 
I think that it requires to much steps in order to make this work ..
What do you think?

**Comment by flovilmart** [comment]
We need to go pull because we can't put unique endpoints to the live query server :)

**Comment by ranhsd** [comment]
Ok , but I expect that after we publish a message the subscriber will receive it immediately.. this is the idea of real time apps.

**Comment by flovilmart** [comment]
In practice this is pretty much immediate :)

**Comment by ranhsd** [comment]
Hi @flovilmart.
If we must go with pull then in order to make it "as real time as possible" what we can do is to call the pull api method after we publish a new message. The pull we be called immediately after a message is being published inside the callback of the publish API .
Now in order to send the message back to the client we still need to use the EventEmitter API 

**So the flow goes like this:** 
1. The client execute a CUD (create,update,delete) operation on one of the classes that was registered under LiveQuery 
2. Publish method is being executed 
3. After the message was published we call the pull pub/sub api to pull the messages from the queue with **returnImmediately** set to true 
4. We loop on the list of messages and emit them so the code of the publish method is:

```
publish(channel, message) {

    const topic = pubsubClient.topic(channel);

    topic.publish({ data: message }, (err, messageIds) => {
      if (err) {
        console.log('error on publish ' + err);
        return;
      }


      const subscription = pubsubClient.subscription(channel);

      subscription.pull({ returnImmediately: true }, (err, messages) => {
        if (err) {
          console.log('error on pull ' + err);
          return;
        }

        messages.forEach((message) => {
          this.emitter.emit(channel, message.data);
        });

        if (messages.length > 0) {
          subscription.ack(messages.map((message) => message.ackId), function () {

          });
        }
      });
    });
  }
```
1. When the emit triggered the handler (under the subscribe method) is being triggered and send the message to the client so the code under the Subscribe method which handle it looks like the following: 

```
  subscribe(channel) {

    const topic = pubsubClient.topic(channel);
    topic.subscribe(channel, (err, subscription) => {
      if (err) {
        return;
      }

      console.log(`Subscription ${subscription.name} created.`);

    });

    let handler = (message) => {
      this.emit('message', channel, message.data);
    }

    this.emitter.on(channel, handler);
  }
```

In this code everything works well, the client send a message and other clients receive it.

So i need 2 things from you :) 
1. What do you think about it? it is ok to call pull each time after we publish a message, it is ok how i use the **emit** and **on** functions of the EventEmitter? 
2. What about unsubscribe? Since we subscribe to the afterSave and afterDelete channels the unsubscribe will never be triggered unless we shut down the server or parse-server will expose API's to enable/disable the live query capability.. 
   I didn't find any place where the unsubscribe triggered (i know that in other scenarios it should but for this scenario i didn't understand when it should be called).

Thanks,
Ran.

**Comment by flovilmart** [comment]
You can't really call the subscriber.pull because ultimately those will be on different servers. Calling subscriber.pull is used when you want to flush pending messages that were not received by any subscription.

Also, I recall you can't call subscribe on the same channel multiple times, each subscription is uniquely identified by it's name. Having 2 live query servers subscribed on the same 'channel' will fail. In my early attempts I appended a UUID to the channel string to make those unique.

Also, you should probably send the message ack back from the subscriber otherwise the same message will be emitted over and over

**Comment by ranhsd** [comment]
Ok I understand but how the subscription will receive the messages? According to GCP docs you can do it by pulling the messages on demand and push the message to an endpoint URL. And push will not work because we cannot define endpoint on live query server so we need to go with pull and from what I understand the only way to receive messages is by pulling them from pub/sub 
According to the subscription.. I can do it but currently I decided to go with one topic and subscription per channel

**Comment by ranhsd** [comment]
Regarding my last response (above) I will add uuid to the subscription but I need to understand when the unsubscribe will be called to unsubscribe it from the pub/sub server

**Comment by flovilmart** [comment]
> I can do it but currently I decided to go with one topic and subscription per channel

Yeah, but we need support for multiple subscribers so the topic would look like `parse-server-{channel}`

and subscriptions you would have `parse-server-{channel}-{uuid}`.

Does that make sense?

**Comment by ranhsd** [comment]
It can be but then it means that we will have only one subscription per topic. What I said is that we can create multiple subscriptions per topic so then we will have a channel (unique identifed) for subscription

But you suggestion seems to work ok so I will try it.. but this is not issue , the issue is with the pull/push of messages and how it should work because like I mentioned above according to the docs we have 2 options
1. Push (with endpoint URL)
2. By pulling the messages from the pub/sub server and acknowledging our pull .

**Comment by flovilmart** [comment]
in the subscriber, you fetch the topic based on the channel (`parse-server-{channel}`) and then create a subscription with the name: `parse-server-{channel}-{uuid}`.

We need to go pull but the pub/sub client fires the event on the subscription when a new message is available for the subscription.

Do you have some code you can push in a PR?

**Comment by ranhsd** [comment]
Yes I have the code that is currently works for me. I will push it and will let you know..
The code is not completed yet so you may see some hard coded values of the project id and key file name . Moreover you will need to create the topic ahead because I didn't added the create topic functionality yet..

**Comment by ranhsd** [comment]
And to add to your response . I understand that it should work like that but the subscriber call back is not triggered when I publish the message so i think it work a bit different from redis pub/sub but maybe I am missings something ..

**Comment by flovilmart** [comment]
Did you implement `subscription.on` ? https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.4.0/pubsub?method=subscription

**Comment by ranhsd** [comment]
Actually no .. looks promising will check it out and let you know soon.

Thanks,
Ran.

**Comment by ranhsd** [comment]
Hi @flovilmart , i have some good news.. it works ! (thanks a lot for your help of course :)) 

The process goes like this: 
1. You create subscription 
2. Inside the subscription callback you can the **.on** function 
3. When a new message received you first acknowledge the pub/sub server that you got it (we must acknowledge because the pub/server server will try to send it over and over if we will not do it) 
4. You call the `self.emit('message', channel, message.data);`   inside the **.on** callback as well in order to pass the message to the client .

Now about unsubscribe.. i didn't managed to call the unsubscribe function , can you tell me when this function should be triggered ?

**Comment by flovilmart** [comment]
I'm not sure when it should be triggered, it doesn't seem unsubscribe is called from anywhere...

**Comment by ranhsd** [comment]
That's what i saw also.. But we need to do some cleanup once in a while no? otherwise we will have a lot of inactive subscriptions in the gcp pub/sub 
I think it should be called when the live query server will be shutting down because the channels that i get are **afterSave** and **afterDelete** etc. which are cloud code events so from what i saw we will always create only 2 subscriptions per topic because the channels are afterSave and afterDelete and there is no **user based subscription**. We will have more than 2 subscriptions only if we will have multiple live query servers (that's the only case) but we must find a way to unsubscribe all the subscriptions under topic .

**Comment by flovilmart** [comment]
Add a listener on SIGINT and SIGTERM, to destroy the open subscriptions.

**Comment by ranhsd** [comment]
Hi , ok will do so.. 
Meantime i commit and push the changes that i did, you can have a look on it if you want. 
We need also to update the README that this is under development.

**Comment by flovilmart** [comment]
awesome!

**Comment by ranhsd** [comment]
It's not finalized  yet.. i still have to do the following: 
1. Auto create topics. 
2. unsubscribe
3. testing with more than 2 devices.. currently i tested it on 2 devices but i want to make sure that there are no issues there..

**Comment by ranhsd** [comment]
@flovilmart , i update the code with auto creation of topics (first i check if the topic already exist and if it is not exist i create it). about the SIGINT and SIGTERM, do you think there is a better solution for that? anyway i expect that the unsubscribe method will be triggered by the core and not by caching the process events... 
Inside the unsubscribe the only thing that we need to do is to delete all the topics and subscriptions in each topic.

**Comment by flovilmart** [comment]
No, only delete the subscription. Not the topic.

**Comment by flovilmart** [comment]
For now the unsubscribe is not called from the parse-server.

**Comment by ranhsd** [comment]
Hi @flovilmart , topics will not be deleted only subscriptions ... but do you think that the unsubscribe will be called by the framework soon or we should implement it on our own?

**Comment by flovilmart** [comment]
We should implement it, but because of the nature of the gcloud pubsub, we should also destroy the subscriptions when the live query server goes down
