### ISSUE TITLE
npm deploy, missing email

### ISSUE THREAD

**Issue by flovilmart** [parse-server-modules/parse-server-gcloud-pubsub#7]
Hey @ranhsd can you add the email field to the travis.yaml, it's [unable to deploy](https://travis-ci.org/#L476)

See https://docs.travis-ci.com/user/deployment/npm/

**Comment by ranhsd** [comment]
Done!

**Comment by flovilmart** [comment]
could you add me on NPM too? I'll be centralizing the credentials at one point :)

**Comment by ranhsd** [comment]
Done.

**Comment by flovilmart** [comment]
Thanks!

**Comment by ranhsd** [comment]
Sure. We need to provide some docs as well on how to use it (starting from GCP cockpit). And maybe to create some tests

**Comment by flovilmart** [comment]
Yep definitely, we're running with GCS and GC-PubSub + Kubernetes and it's pretty nice :)

**Comment by ranhsd** [comment]
We are running the same stack but currently we use Redis pub-sub. But i am working on changing it to google cloud pub sub (in production). We are running everything on GKE.
