### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS env variable

### ISSUE THREAD

**Issue by ranhsd** [parse-server-modules/parse-server-gcloud-pubsub#8]
Hi @flovilmart 
do you think the GOOGLE_APPLICATION_CREDENTIALS env variable should be required or not? i am asking because if you use google app engine or google container engine you don't need to provide credentials for pub sub or any other services which available (on the same project)

**Comment by flovilmart** [comment]
Yep probably, is the GCLOUD_PROJECT var available?

**Comment by ranhsd** [comment]
Hi @flovilmart 
from some reason the value is **undefined**. I tried also GCP_PROJECT_ID and this is also undefined. It's very strange because i am running inside container engine and i remember that few months ago i was able to get the GCP_PROJECT_ID 
BTW! in the GCS adapter (google cloud storage) it works and i don't send any project id or credentials .

**Comment by ranhsd** [comment]
Ok. after tested it on a real system i found out that you don't need to send any env variable in order to work with pub sub. This assumption is correct only if you consume the pub sub service **from the same project where your container engine run** if from some reason your pub sub service is located on a different project then you need to provide the GCLOUD_PROJECT + GOOGLE_APPLICATION_CREDENTIALS. 

So from my POV those env variable are not required variables and i think we should let the google pub sub module to handle exceptions (in case those variables were not provided in other deployment scenarios)

**Comment by flovilmart** [comment]
even on GKE managed by kubernetes?

**Comment by ranhsd** [comment]
@flovilmart yes i run it inside GKE . tested it on a separate namespace and it worked. I didn't provide anything the only thing that you need to check is that your GKE cluster has permissions to access the pub/sub service you can do from the GCP console.

<img width="303" alt="screen shot 2017-04-20 at 23 59 14" src="https://cloud.githubusercontent.com/assets/3685671/25252368/66bd177c-2625-11e7-9f64-a561fd6f8674.png">

Please notice that **Cloud Pub/Sub** is **enabled**

**Comment by ranhsd** [comment]
Hi @flovilmart i am using config.json for my parse server (and not env. variables) and i am trying to add configure that gcloud pub sub. So my config file looks like the following:

`  "liveQuery": {
        "pubSubAdapter": {
            "module": "parse-server-gcloud-pubsub"
        },
        "classNames": [
            "CLASS1",
            "CLASS2"
        ]
    },`

Because i am using k8s i decoupled my live query server from my parse server and there i load pub sub via code so what i did is the following: 

`
const PubSub = require('@google-cloud/pubsub');
const pubsubClient = PubSub();
ParseServer.createLiveQueryServer(httpServer, {
  appId: nconf.get("appId"),
  masterKey: nconf.get("masterKey"),
  serverURL: nconf.get("serverURL"),
  pubSubAdapter: pubsubClient
});
`

From some reason it is not working for me it was worked before when i implemented this library but not it's not working. Can you please provide some details on how to config it for both parse-server (via config.json file) and for live query (via code)

thanks.

**Comment by flovilmart** [comment]
```
    /* for publishing */
  'liveQuery': {
    'classNames': ['partyInfo'],
    'pubSubAdapter': 'parse-server-gcloud-pubsub',
  },
  /* for the subscriptions */
  'liveQueryServerOptions': {
    pubSubAdapter: 'parse-server-gcloud-pubsub',
  },
  'startLiveQueryServer': true,
```

That's our config :)

**Comment by ranhsd** [comment]
Hi @flovilmart. Thanks! 
So according to your config it looks like you did not decouple the live query server from the main server right ?

**Comment by flovilmart** [comment]
Nope not yet, but the config should be quite similar, it's all started and up correctly. You can also use the CLI for the LQS server only.

**Comment by flovilmart** [comment]
In you decoupling, you're using the the pubsub  client and not the adapter:

```
const PubSub = require('@google-cloud/pubsub'); const pubsubClient = PubSub(); ParseServer.createLiveQueryServer(httpServer, { appId: nconf.get("appId"), masterKey: nconf.get("masterKey"), serverURL: nconf.get("serverURL"), pubSubAdapter: pubsubClient });
```

Should Be

```
ParseServer.createLiveQueryServer(httpServer, { appId: nconf.get("appId"), masterKey: nconf.get("masterKey"), serverURL: nconf.get("serverURL"), pubSubAdapter: { module: "parse-server-gcloud-pubsub"} });
```

**Comment by ranhsd** [comment]
Hi @flovilmart , thanks i noticed this and now i get another error (which may effect on your side as well i think) the error is: 

> Failed to create subscription Error: Invalid resource name given (name=projects/myproj-test/subscriptions/parse-server-8o0XCNfrZScGf6117bhggd7J6ySOImmXGkcJrN21V6A=afterDelete-20e3e030-269f-11e7-aea5-0bc31be30bd6).

Do you know what is the issue here?

**Comment by flovilmart** [comment]
Odd there is an = sign in the UUID used to identify the subscription

**Comment by flovilmart** [comment]
Ah it's your applicationID that contains =?

**Comment by ranhsd** [comment]
Yes it is ... I will remove it and retry. BTW do we have some instructions on how to appId should be created? It happened to me before with the **/** character.

**Comment by flovilmart** [comment]
Just `[a-zA-Z0-9]+` is fine.

See: https://github.com/parse-community/parse-server/blob/master/bootstrap.sh#L22

**Comment by ranhsd** [comment]
that's nice. I will use it. 
From some reason it looks like that Redis pub sub is much faster than gcloud pub sub. I just replaced to use gcloud pub sub and there is some delay that i didn't had with the Redis pub sub (i am using it in chat)

**Comment by flovilmart** [comment]
That makes sense, redis is centralized, real time KV store, 
Pubsub is a decentralized message queue

**Comment by ranhsd** [comment]
Yes but the big advantage of the gcloud pub sub is that it auto scales as you growth

**Comment by flovilmart** [comment]
I wasn't saying there was a drawback for us compared to Redis.

**Comment by ranhsd** [comment]
Did you use Redis in your k8s cluster before or your Redis server was outside of your cluster? I am asking because one of main adv. of k8s is that you can consume internal services which is very fast

**Comment by flovilmart** [comment]
nope, no redis.

**Comment by TimNZ** [comment]
Hi, sorry, Google Cloud noob here.

I deployed Parse Server to GAE, using instructions here: https://github.com/parse-community/parse-server/issues/2798

Get the 'connect' event for a live query subscription, but no data events.

In my GAE instance GOOGLE_APPLICATION_CREDENTIALS is not defined in the environment, even though I've create default service settings via Credentials.

The way I read #10, this env var should already exist, but doesn't.  
GCLOUD_PROJECT,GOOGLE_CLOUD_PROJECT etc are present.

I can't find any docs explicitly saying that GOOGLE_APPLICATION_CREDENTIALS env should be  defined.

Am I misreading this, or do I explicitly need to deploy the json file and specify GOOGLE_APPLICATION_CREDENTIALS in app.yaml?

**Comment by TimNZ** [comment]
I switched to Redis seeing as it was a quick job.  
I'd like to one day contribute to getting started guides for a range of scenarios, having to piece together tips from issues, guides etc was a bit painful.

**Comment by flovilmart** [comment]
It’s more efficient to use redis as well.

**Comment by TimNZ** [comment]
Because I don't like unexplained things I can't find published official answers for; is GOOGLE_APPLICATION_CREDENTIALS environment var supposed to be defined in a GAE instance?

**Comment by flovilmart** [comment]
See instructions / docs here: https://developers.google.com/identity/protocols/application-default-credentials

**Comment by flovilmart** [comment]
> If you are running in Google App Engine production, the built-in service account associated with the application will be used.

**Comment by TimNZ** [comment]
Thanks your time in replying.

I had already read that page, and re-read this issue a couple of times, and as far as I can tell, I don't need to do anything special beyond specifying the adapter in my config and it should have worked.  
My Parse server and Live Query server are running on the same GAE instance and Pub/Sub is enabled.
Anyway I won't spend time on it, Redis is working.
I'll have a look later.
